project:
  type: website
  output-dir: docs

website:
  title: "Mark Holmes"
  navbar:
    left:
      - about.qmd
      - articles.qmd
      - collaborators.qmd
      - beeg-brain.qmd

format:
  html:
    theme: 
      dark: cyborg
      light: sandstone
    css: styles.css
    toc: true

author: 
  - name: Mark Holmes
    email: mark.j.holmes.95@gmail.com

execute: 
  cache: true

date: today
code-fold: show