project:
  type: website
  output-dir: docs

website:
  title: "Mark Holmes"
  navbar:
    left:
      - about.qmd
      - articles.qmd
      - collaborators.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
